{% set version = "2.0.4" %}
{% set sha256 = "1733e2e5f0fe12389acfaab9aff613d0405855c7aa802c1ca624652168255187" %}

package:
  name: ecos
  version: {{ version }}

source:
  fn: simplejson-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/ecos/ecos-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pip
    - scipy

  run:
    - python
    - numpy
    - scipy
test:
    files:
      - ..\..\src\test_interface.py
      - ..\..\src\test_interface_bb.py
    requires:
      - nose
    imports:
      - ecos
    commands:
      - nosetests --nocapture test_interface.py
      - nosetests --nocapture test_interface_bb.py

about:
  home: https://github.com/embotech/ecos-python
  license: GPLv3
  summary: Embedded cone solver for second-order cone programs
  description: |
    This is the Python package for ECOS: Embedded Cone Solver. 
    See Github page for more information.
  doc_url: https://www.embotech.com/ECOS
  dev_url: https://github.com/embotech/ecos

extra:
  recipe-maintainers:
    - Enzo Busseti
