package:
  name: cvxpy
  version: "1.0.1"

source:
  git_url: https://github.com/cvxgrp/cvxpy
  git_tag: v1.0.1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cvxpy = cvxpy:main
    #
    # Would create an entry point called cvxpy that calls cvxpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - setuptools
    - six
    - toolz
    - cvxcanon >=0.0.22
    - fastcache
    - python
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - numpy >=1.9
    - scipy >=0.15
    - libgcc
    - lapack


  run:
    - python
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - fastcache
    - six
    - toolz
    - numpy >=1.9
    - scipy >=0.15
    - cvxcanon >=0.0.22
    - libgcc
    - lapack

test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.cvxcore
    - cvxpy.cvxcore.python
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.problems.problem_data
    - cvxpy.problems.solvers
    - cvxpy.reductions
    - cvxpy.reductions.complex2real
    - cvxpy.reductions.complex2real.atom_canonicalizers
    - cvxpy.reductions.dcp2cone
    - cvxpy.reductions.dcp2cone.atom_canonicalizers
    - cvxpy.reductions.eliminate_pwl
    - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
    - cvxpy.reductions.qp2quad_form
    - cvxpy.reductions.qp2quad_form.atom_canonicalizers
    - cvxpy.reductions.eliminate_pwl.atom_canonicalizers
    - cvxpy.reductions.solvers
    - cvxpy.reductions.solvers.conic_solvers
    - cvxpy.reductions.solvers.qp_solvers
    - cvxpy.reductions.solvers.lp_solvers
    - cvxpy.tests
    - cvxpy.transforms
    - cvxpy.utilities
    - cvxpy.cvxcore.python

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: Apache 2.0
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
